# Generated by Django 5.0.6 on 2024-06-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('CR', 'curd'), ('ML', 'milk'), ('LS', 'lassi'), ('MS', 'Milkshake'), ('PN', 'paneer'), ('GH', 'Ghee'), ('CZ', 'cheese'), ('IC', 'ICe-Cream'), ('NE', 'neettea')], max_length=2)),
                ('products_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
